spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true